### ISSUE TITLE
Backend is available to unwanted clients by default

### ISSUE THREAD

**Issue by alopatindev** [KCGD/ytmpv#1]
Thanks for this awesome project!

Listening on wildcard host is likely not what average user wants (especially if one is not under NAT). It'd be nice to either have additional option `--host=0.0.0.0` with `--host=localhost` as default, or just:

```patch
diff --git a/src/main.ts b/src/main.ts
index 534fdc4..11da7a8 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -99,6 +99,6 @@ function Main(): void {
                 response.end("YTMPV is running!");
             }
         }
-    }).listen(ProcessArgs.port);
+    }).listen(ProcessArgs.port, 'localhost');
     Log(`I`, false, `Binded to port ${ProcessArgs.port}`);
 }
```

**Comment by KCGD** [comment]
Ooh yeah, good catch! I'll get on implementing this as soon as I can

**Comment by KCGD** [comment]
Fixed in [this](https://github.com/KCGD/ytmpv/commit/31e4961fc8735cc187addc8b8cd0ae53c0018d8a) commit :)
